# Generated by Django 5.0 on 2024-01-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_ussername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ussername',
        ),
    ]
